export const EMAIL_INCORRECT_PATTERN = "auth.EMAIL_INCORRECT_PATTERN";
export const PASSWORD_NOT_STRING = "auth.PASSWORD_NOT_STRING";
export const PASSWORD_MIN_LEN_FAILED = "auth.PASSWORD_MIN_LEN_FAILED";
export const PASSWORD_REQUIREMENTS_NOT_MET =
  "auth.PASSWORD_REQUIREMENTS_NOT_MET";
